spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/${ENV_NAME:test}
  profiles:
     active: native

server:
  port: 8001

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:}