spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/test
  profiles:
     active: native

server:
  port: 8001

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:324cF7dt-3720-45w4-b28C-4N3b9e1960cS}